//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class portaltable
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string FamilyName { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string BirthDate { get; set; }
        public string BirthPlace { get; set; }
    }
}
